### ISSUE TITLE
lower speed

### ISSUE THREAD

**Issue by akamizi** [gwlim/openwrt-sfe-flowoffload#1]
with my model TP-Link TL-WR1043N/ND v1, with the same configurations and in lan (not wifi), the speed with http://www.speedtest.net/ went from 500Mbps to ~250Mbps
I downgraded

**Comment by gwlim** [comment]
Did you enable SFE?
Only basic features are enabled at startup in new firmware.

**Comment by akamizi** [comment]
I started the service and tried various combinations with flow offload active and inactive, and restarted, but the best speed obtained was 340Mbps

**Comment by akamizi** [comment]
I'm trying to flash again with the factory version (my model is 32M)

**Comment by demorphica** [comment]
just wanted to understand how do we make the decision on whether to enable SFE or Flow Offload?
Are there any considerations which would help decide?
