### ISSUE TITLE
JAN 2019 -images (wdr4300_

### ISSUE THREAD

**Issue by asergiu** [gwlim/openwrt-sfe-flowoffload#10]
Hi
Tested you January images - not sure is related to your image or Flow offlaod  but the upload is badly impacted by the Flow offload -actually halved in my case. 
I did a repeated test with and without flow offload checked (check and service enabled and disabled and the results are 
always around these:

**Without Flow offlaod :**

![flow-sfe-disabled](https://user-images.githubusercontent.com/1842671/51075774-e687a480-1698-11e9-9e8b-313be3a5e08f.png)

----------------------------------------------------------------------------------------

**With flow offloading :**

![flow-sfe-enabled](https://user-images.githubusercontent.com/1842671/51075778-f2736680-1698-11e9-96d1-b674fe445b9f.png)

AS you can see the download is benefitting from this but the upload goes down. My connection is **500Mb -down with 250 Mb/upload** roughly.

**Comment by asergiu** [comment]
seems that without ticking flow offload - and just leaving the SFE service on - gets around 416Mb/s download and 240 Mb/s upload
![image](https://user-images.githubusercontent.com/1842671/51076004-b1c91c80-169b-11e9-8189-1afe0b302e85.png)

**Comment by elgab** [comment]
Yes, that is normal-ish.
for Digi gigabit PPPoE best performing implementation is SFE.
the overclocked 720Mhz WDR3600 is doing 800mbit down + full 500mbit up RDS PPPoE.

**Comment by asergiu** [comment]
Yep - my connection is 500 down/250 Up max.
So SFE is around there.... 
you can close this.
