### ISSUE TITLE
Unable to install software package named Dnydns :(

### ISSUE THREAD

**Issue by Zsolteeca** [gwlim/openwrt-sfe-flowoffload#101]
I tried to install the dyndns package to the new firmware (dec2019) and I got the following error

"RPCError

RPC call to luci.ddns/get_services_status failed with error -32002: Access denied
  at handleCallReply (http://192.168.1.88:13360/luci-static/resources/rpc.js?v=git-19.348.21714-7b0ae11:12:3)"

:(

**Comment by gwlim** [comment]
Upstream Luci based apps are broken due to Luci transitioning from Lua backend to JS backend.
It is not likely to get fix anytime soon.
Workaround: use commandline to configure dyndns

**Comment by Zsolteeca** [comment]
Thank you

I found a solution to this problem if anyone would face


"Try

chmod +x /usr/libexec/rpcd/luci.ddns
service rpcd restart"

And now the ddns service is working :)

**Comment by Zsolteeca** [comment]
I have found this solution which partially fix this software component..

"Please try

chmod +x /usr/libexec/rpcd/luci.ddns
service rpcd restart"

**Comment by joshenders** [comment]
> I have found this solution which partially fix this software component..
> 
> "Please try
> 
> chmod +x /usr/libexec/rpcd/luci.ddns service rpcd restart"

Thanks for sharing this. This resolved the issue for me. This issue still affects OpenWRT SNAPSHOT `r18539-f2c3875dfc` and `luci-app-ddns` version: `git-21.187.20976-699b7f0`
