### ISSUE TITLE
kmod-fs-ext4 is not work

### ISSUE THREAD

**Issue by brick2008** [gwlim/openwrt-sfe-flowoffload#103]
Hi,I'm using JAN-2020 normal firmware on TP-Link 4300 v1,exec opkg install kmod-fs-ext4 and reboot,I can not mount USB disk.
Could you please compile the normal firmware with ext4 support? or fix that problem?

Sat Dec 28 16:43:39 2019 user.info kernel: [  241.264690] kmodloader: loading kernel modules from /etc/modules.d/*
Sat Dec 28 16:43:39 2019 kern.warn kernel: [  241.279458] jbd2: Unknown symbol set_freezable (err -2)
Sat Dec 28 16:43:39 2019 kern.warn kernel: [  241.285042] jbd2: Unknown symbol __refrigerator (err -2)
Sat Dec 28 16:43:39 2019 kern.warn kernel: [  241.290844] jbd2: Unknown symbol freezing_slow_path (err -2)
Sat Dec 28 16:43:39 2019 kern.warn kernel: [  241.296812] jbd2: Unknown symbol system_freezing_cnt (err -2)
Sat Dec 28 16:43:39 2019 kern.warn kernel: [  241.311210] jbd2: Unknown symbol set_freezable (err -2)
Sat Dec 28 16:43:39 2019 kern.warn kernel: [  241.316837] jbd2: Unknown symbol __refrigerator (err -2)
Sat Dec 28 16:43:39 2019 kern.warn kernel: [  241.322773] jbd2: Unknown symbol freezing_slow_path (err -2)
Sat Dec 28 16:43:39 2019 kern.warn kernel: [  241.328916] jbd2: Unknown symbol system_freezing_cnt (err -2)
Sat Dec 28 16:43:39 2019 user.err kernel: [  241.336246] kmodloader: 2 modules could not be probed
Sat Dec 28 16:43:39 2019 user.err kernel: [  241.341750] kmodloader: dependency not loaded jbd2
Sat Dec 28 16:43:39 2019 user.err kernel: [  241.346984] kmodloader: - ext4 - 1
Sat Dec 28 16:43:39 2019 user.err kernel: [  241.350790] kmodloader: - jbd2 - 0

**Comment by gwlim** [comment]
```
root@openwrt:~# ls /tmp/*.ipk
/tmp/kmod-crypto-crc32c_4.19.91-1_mips_24kc.ipk
/tmp/kmod-fs-ext4_4.19.91-1_mips_24kc.ipk
/tmp/kmod-lib-crc16_4.19.91-1_mips_24kc.ipk
/tmp/kmod-lib-crc32c_4.19.91-1_mips_24kc.ipk
root@openwrt:~# opkg install /tmp/*.ipk
Installing kmod-crypto-crc32c (4.19.91-1) to root...
Installing kmod-fs-ext4 (4.19.91-1) to root...
Package kmod-lib-crc16 (4.19.91-1) installed in root is up to date.
Installing kmod-lib-crc32c (4.19.91-1) to root...
Configuring kmod-crypto-crc32c.
Configuring kmod-lib-crc32c.
Configuring kmod-fs-ext4.
root@openwrt:~# insmod ext4
module is already loaded - ext4
root@openwrt:~#

```
