### ISSUE TITLE
JAN 2020 sysupgrade image for 1043ND v2 issue

### ISSUE THREAD

**Issue by 0sy** [gwlim/openwrt-sfe-flowoffload#104]
https://github.com/gwlim/openwrt-sfe-flowoffload/blob/master/JAN-2020/openwrt-sfe-flowoffload-normal/TP-Link%20WR1043NDv2-mips74k-ath9k/openwrt-ath79-generic-tplink_tl-wr1043nd-v2-squashfs-sysupgrade.bin

Ends up with https://i.imgur.com/L0Wuzzo.png

Edit: I'm on the DEC 2019 image

**Comment by elgab** [comment]
The files could get corrupted, maybe @gwlim can help us in the future with some SHA256 or GPG signatures.

**Comment by yonizaf** [comment]
I tried the specified file. It flashed and worked fine.

**Comment by Zsolteeca** [comment]
I also flashed the firmware I have the same modell of the router what you have.

**Comment by 0sy** [comment]
Yeah, I tried again and it worked. Weird how the first two attempts failed.

OPENWRT_RELEASE="OpenWrt SFE r11797-1579599079"
