### ISSUE TITLE
Wr1043nd v1 32Mb only mini

### ISSUE THREAD

**Issue by varma86** [gwlim/openwrt-sfe-flowoffload#108]
I installed the mini version onto my Wr1043nd v1 (with stock 32MB of RAM) but the flash memory is shrienked to 4 MB, making quite impossible installing packages. The internal flash memory is 8MB, why has been reduced to 4MB?
Thank you for your builds and your overclocked version of u-boot!

**Comment by Zsolteeca** [comment]
How many space have you got to install packages?
I have got Tplink WR1043ND v2 (64MB mem) router and I have 1,7MB to install what I would like to use..

**Comment by gwlim** [comment]
4MB free and 4MB total is 2 different thing
