### ISSUE TITLE
wdr4900 v1 - nlbwmon process 100% cpu time

### ISSUE THREAD

**Issue by cosminsstoica** [gwlim/openwrt-sfe-flowoffload#110]
On the latest build (feb2020) I have an issue with bandwidth monitor. It uses 100% of cpu time after few days of usage. 

![image](https://user-images.githubusercontent.com/20394610/72590124-b7d48780-3905-11ea-95e6-46fb1bd46220.png)

**Comment by Zsolteeca** [comment]
If you restart the service what will be happen with the cpu usage?

**Comment by cosminsstoica** [comment]
After service restart the cpu usage is returning to normal.

**Comment by cosminsstoica** [comment]
Looks like the problem is solved. 
https://github.com/jow-/nlbwmon/issues/30
