### ISSUE TITLE
Upgrade from standard OpenWRT possible?

### ISSUE THREAD

**Issue by goforthanddie** [gwlim/openwrt-sfe-flowoffload#114]
Hey there,

first, thanks for your effort! Is it possible to use the sysupgrade image when my device is running a standard OpenWRT installation? Or is it possible to use the factory image when having a standard OpenWRT installation? Or do I have to go all the way back to using the stock image and starting over again with the factory image? Maybe this could go into the FAQ.

Thanks

Samy

**Comment by gwlim** [comment]
Sysupgrade will do
