### ISSUE TITLE
Latest 19.07.1 for TP-Link Archer C7v5-mips74k-ath10k

### ISSUE THREAD

**Issue by tdimeco** [gwlim/openwrt-sfe-flowoffload#116]
Hi @gwlim,

The latest 19.07.1 version of OpenWRT [fixes an issue](https://openwrt.org/releases/19.07/notes-19.07.1) with 5 GHz Wireless. Are you planning a new build (especially for the TP-Link Archer C7v5)?

Thank you very much for your work!

Thomas

**Comment by zigagrcar** [comment]
Upvoting, there really seems to be some kind of performance issue. :thumbsup:

**Comment by gwlim** [comment]
Added MAR 2020

**Comment by tdimeco** [comment]
Thank you so much! 👍
