### ISSUE TITLE
TP-Link WR1043NDv1-32MB-RAM-mips24k-ath9k

### ISSUE THREAD

**Issue by dreamer7** [gwlim/openwrt-sfe-flowoffload#119]
In system log 

Mon Apr  6 11:26:14 2020 daemon.err hostapd: nl80211: NL80211_ATTR_STA_VLAN (addr=40:9c:28:3c:c5:b5 ifname=wlan0 vlan_id=0) failed: -2 (No such file or directory)

This happens when connecting a client with iOS. I read that I need WPA3 PSK, SAE works on 1043v3. on v1 no. and there and there installed wpad-openssl. on 1043 v1 wlan0 not start with SAE.

**Comment by gwlim** [comment]
The radio on AR9132 is too old to support SAE because Openwrt mandate the use of MFP Protection for SAE.
If you feel strongly about this bring it up with OpenWRT
