### ISSUE TITLE
WNDR3700v1

### ISSUE THREAD

**Issue by robcore** [gwlim/openwrt-sfe-flowoffload#12]
Hi there! 
Thanks for all of your hard work.  Would you be open to adding the Netgear WNDR3700v1 to supported devices?  It is similiar to the v4, but has a different cpu.  It is ar7xx, however, and i think would work well.
Take care!
Rob

**Comment by gwlim** [comment]
Next release

**Comment by robcore** [comment]
> Next release

Thanks so much, man!  Though if you're doing it just for me, you could save yourself the effort because I'm picking up a used V4 tomorrow from someone in my city (lucky, right?).

**Comment by gwlim** [comment]
Added support for WNDR3700v1

**Comment by robcore** [comment]
Thank you :)

**Comment by gwlim** [comment]
Added overclocked image for 800MHZ ar7161 based on overclock patch available online.
Please try ONLY if you know how to recover using uboot/redboot loader.
It will be a permanent thing only if I know it works
