### ISSUE TITLE
kmod-mtd-rw overclock package?

### ISSUE THREAD

**Issue by MrObvious** [gwlim/openwrt-sfe-flowoffload#122]
I really appreciate this build and your work gwlim! I was just wondering if this package was available somewhere (as I'm not into compiling yet for OpenWRT) to try my hands at overclockIng?

**Comment by gwlim** [comment]
https://github.com/gwlim/openwrt-sfe-flowoffload/blob/master/MAR-2020/openwrt-sfe-flowoffload-normal/TP-Link%20Archer%20C7v2-mips74k-ath10k/kmod-package.tar.gz
