### ISSUE TITLE
Archer C7 v4 throughput higher on DD-WRT SFE than on OpenWRT SFE

### ISSUE THREAD

**Issue by 04dco** [gwlim/openwrt-sfe-flowoffload#123]
DD-WRT also has SFE and it is enabled by default. I get higher WAN throughput with their implementation.
https://dd-wrt.com/support/other-downloads/?path=betas%2F2020%2F04-18-2020-r42925%2Ftplink_archer-c7-v4%2F

DD-WRT: https://www.speedtest.net/result/8021161826.png
OpenWRT: https://www.speedtest.net/result/9078438403.png

**Comment by gwlim** [comment]
1) Do not use speedtest, the most accurate test is if you run both client and server yourself
2) If you must use a web test use https://fast.com/ instead, it is both IPv4 and IPv6 capable and their servers are better maintained

**Comment by 04dco** [comment]
OpenWRT: ![2020-04-18_18-27](https://user-images.githubusercontent.com/56886463/79644445-bb500700-81b1-11ea-8794-3e13d5a762ea.png)
https://www.dslreports.com/speedtest/62441297

DD-WRT: ![2020-04-18_19-48](https://user-images.githubusercontent.com/56886463/79644457-cd31aa00-81b1-11ea-8ec7-2659af5a5bfb.png)
https://www.dslreports.com/speedtest/62442055

All tests were done with the default configuration and WiFi disabled.

**Comment by gwlim** [comment]
Added new option
echo 1 > /sys/fast_classifier/skip_ingress_qdisc

**Comment by MrObvious** [comment]
Is this on the May build?

**Comment by gwlim** [comment]
Yes although I still don't think the issue is with SFE
When the router just booted a lot processes are eating up the cpu, you should let the router idle and the line idle for a while before testing
