### ISSUE TITLE
archer c7 v2 kmod-usb-storage kernel not compatible.

### ISSUE THREAD

**Issue by jinglei207** [gwlim/openwrt-sfe-flowoffload#125]
im trying to install kmod-usb-storage but got a kernel not compatible message.

**Comment by Zsolteeca** [comment]
Did you try to install it from tarball archive?

**Comment by jinglei207** [comment]
> Did you try to install it from tarball archive?
> File name:kmod-package.tar.gz
> It is on the same place where your firmware is located.

Thanks a lot, didn't see that!
