### ISSUE TITLE
can't find filesystem packages for archer c7 v2

### ISSUE THREAD

**Issue by jinglei207** [gwlim/openwrt-sfe-flowoffload#127]
I'm trying to mount fat32 usb driver and ext4 hhd, but can't find the package for archer c7 v2.
kmod-fs-ext4
kmod-fs-vfat

**Comment by Zsolteeca** [comment]
Are you sure? I downloaded the tarball archived package from dir Archer c7 v2 and I found these two packages.

**Comment by jinglei207** [comment]
> Are you sure? I downloaded the tarball archived package from dir Archer c7 v2 and I found these two packages.

sorry, i re-extracted the the archive and found it.
