### ISSUE TITLE
TP Link Archer C7 V2 overclock possible?

### ISSUE THREAD

**Issue by balajisraghavan** [gwlim/openwrt-sfe-flowoffload#132]
Thanks for taking the time to provide the sfe-flowoffload releases. Reading though the issues, I see mentions of overclocking routers. Could you please clarify if there's a way to overclock the Archer C7 V2 CPU and memory?

**Comment by gwlim** [comment]
Yes it is possible but I can't test and you can't recover so I suggest go to openwrt forums to look for help
