### ISSUE TITLE
WNDR3800ch

### ISSUE THREAD

**Issue by shing3232** [gwlim/openwrt-sfe-flowoffload#15]
Hi, 
Thanks for your hard work. Would you like to add WNDR3800ch to next builds. WNDR3800ch use different hardware from WNDR3700V4.I am a bet worry to use the firmware from WNDR3700V4, so WNDR3800 build would be nice.
Thanks!
SHING

**Comment by gwlim** [comment]
Added in FEB 2019 release

**Comment by gwlim** [comment]
Added overclocked image for 800MHZ ar7161 based on overclock patch available online.
Please try ONLY if you know how to recover using uboot/redboot loader.
It will be a permanent thing only if I know it works
