### ISSUE TITLE
How can I disable flow offloading in Luci?

### ISSUE THREAD

**Issue by Zsolteeca** [gwlim/openwrt-sfe-flowoffload#158]
Because my throughout speed was lower because of this. Later the firmware has got SFE on/off setting and Flow offload on/off setting.. Now the whole SFE+Flow offload are in one :(

**Comment by medium2** [comment]
<a href="https://ibb.co/YdCYJNs"><img src="https://i.ibb.co/YdCYJNs/chrome-IIw-O9-SUylr.png" alt="chrome-IIw-O9-SUylr" border="0"></a>

Try disable all options in the picture attached.
