### ISSUE TITLE
kmod-usb-printer

### ISSUE THREAD

**Issue by azinchen** [gwlim/openwrt-sfe-flowoffload#16]
Please add kmod-usb-printer

**Comment by gwlim** [comment]
Added in MAR 2019

**Comment by thomasrc** [comment]
Is it possible that kmod-usb-printer is missing from the latest build (AUG-2019)? I updated my Archer C7v2 and the mentioned package is not listed under the "installed" tab.

**Comment by azinchen** [comment]
> Is it possible that kmod-usb-printer is missing from the latest build (AUG-2019)? I updated my Archer C7v2 and the mentioned package is not listed under the "installed" tab.

As I understand, all kmod- are removed from firmware, but compiled and distributed along with firmware. You can copy and install necessary kmods manually from kmod-package.tar.gz file.

**Comment by thomasrc** [comment]
Ah, I see. Sorry, I missed that part of the changelog. :D
