### ISSUE TITLE
Some benchmarks with RB450G

### ISSUE THREAD

**Issue by eisengrau** [gwlim/openwrt-sfe-flowoffload#20]
Hello,

Not exactly issues, I just did some jperf benchmarks with my RB450G. Basically the below images speak to themselves:
<img width="800" alt="iperf_mikrotik_4_fe_final" src="https://user-images.githubusercontent.com/42865787/52521915-fd60ed00-2c7e-11e9-919c-6ea9a692f483.png">

The above is with sortcut-fe enabled. flowoffload will yield similar results. Enabling both will degrade the performance a bit, but not as much as below:

So this is WITHOUT any of sortcut-fe or flowoffload enabled:
<img width="800" alt="iperf_mikrotik_3_nofe" src="https://user-images.githubusercontent.com/42865787/52521924-19648e80-2c7f-11e9-87f0-4d68b16801fe.png">

The router was running OpenWrt SFE r8810-09004e6e13 (the january release), and with the stock 680Mhz clock. Overclocking it to 800Mhz will possible allow it to go beyond 1000, but that I haven't tried... So, as you can see, using gwlim's images, the RB450G will perfectly handle consumer Gigabit WAN (as we all know, residential fibre gigabit will never achieve that speed - an ISPs guaranteed link speed is 0kbps)!

**Comment by gwlim** [comment]
Nice! 👍 
Thanks for the feedback!

**Comment by gwlim** [comment]
To add on to test effects of SFE and  SQM
1)To test SFE, turn on SFE enable and start
Test jperf > 900Mbps
2)To test Traffic passthough QDISC even when SFE is enabled, turn on SQL Cap Rate Limit to 300Mbps
Notice that jperf < 300Mbps
3)To test maximium possible SQM with SFE, set SQM to 900Mbps
Notice that jperf graph is fluctuating, jperf < 400Mbps
Therefore maximium performance with SFE and SQM  = < 400Mbps
