### ISSUE TITLE
SQM: The installed version of package kernel is not compatible, require 4.14.98-1-6da5e890… while 4.14.95-1-327182cc… is installed.

### ISSUE THREAD

**Issue by makruiten** [gwlim/openwrt-sfe-flowoffload#21]
I have a dependency problem when I try to install SQM on a 32MB TL-WR1043ND with the FEB-2019 build installed. Can I install it anyway?

**Comment by makruiten** [comment]
Wouldn't it be better to build with the same kernel as all the package are built against?

**Comment by Riotous** [comment]
@makruiten Isn't it just because gwlim's builds are running a newer kernel?

**Comment by makruiten** [comment]
Yes and no. It’s a newer kernel than what is used for these devices in the official builds, but older than the kernel used for some other devices. In this case opkg complains that the kernel is older than the one that is required by the package. It looks to me like this could be fixed by using the same (newer) kernel version, but that’s just an assumption.

**Comment by makruiten** [comment]
Or maybe it is the same kernel: https://openwrt.org/releases/18.06/notes-18.06.2. But then I don’t understand why the package requires a newer kernel than the one installed.

**Comment by gwlim** [comment]
What is the name of the package that triggered this message?
I will try to add that the mini builds are really quite full just adding 1 package would cause it not to build.

**Comment by makruiten** [comment]
It was luci-app-sqm, so I guess you left it out exactly for that reason :)

Whenever you build a new image, do you then use the same kernel as the packages in the [current snapshot](https://downloads.openwrt.org/snapshots/packages/mips_24kc/)? If that's the case, I can wait for your next build and then install SQM while it's fresh. I'm not in a hurry!

**Comment by gwlim** [comment]
The thing is luci-app-sqm should not have any dependency on the linux kernel, it pulls some other packages that depend on the kernel. kmod-something

**Comment by gwlim** [comment]
Sorry accidentally close the issue

**Comment by makruiten** [comment]
I see! I can check that, but right now the router is in use with an official build on it, so I'll have to check that later. Judging from the current installed packages, that would probably include kmod-sched-cake and kmod-sched-core.

**Comment by gwlim** [comment]
I checked dependency includes kmod-ifb and kmod-sched-core, modules added.
Reopen if there are still missing dependencies.

**Comment by makruiten** [comment]
I can't get it to install:

![deps](https://user-images.githubusercontent.com/6661233/53695738-933ff180-3dbf-11e9-951e-b5d01e71aa8c.png)

```
root@TL-WR1043ND:~# opkg install luci-app-sqm
Installing luci-app-sqm (1.3.0-1) to root...
Downloading http://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/luci-app-sqm_1.3.0-1_all.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-sqm:
 * 	kernel (= 4.14.103-1-7b96d9ca0358834b880712b6d716f275)
 * opkg_install_cmd: Cannot install package luci-app-sqm.
```

**Comment by gwlim** [comment]
Added Kernel modules added based on the dependency tree.
Please try again

**Comment by makruiten** [comment]
I think that you've put the image it in the normal directory instead of the mini directory, but it's still the mini build, right? I'll test it.

**Comment by makruiten** [comment]
Installation now succeeds, thanks a lot! I'll leave the issue open, since it's now in the wrong directory of the repo.

**Comment by gwlim** [comment]
Bummer put the files in wrong directory, thanks for the heads up.
