### ISSUE TITLE
Archer C7 V1.x build

### ISSUE THREAD

**Issue by bitcoin1192** [gwlim/openwrt-sfe-flowoffload#23]
Can you build image for this router ? thank you.

**Comment by gwlim** [comment]
Added in MAR 2019, however do note that Wireless AC feature for this board has a hardware bug, the only solution is to replace the wireless module board.
For this router it has a PCI replacable module

**Comment by d687r02j8g** [comment]
Is it possible to do a build for this please? I understand that it requires ath10k and ath10k-firmware-qca988x to be removed from the build profile.
