### ISSUE TITLE
WDR4300/MW4530R with 16mb flash

### ISSUE THREAD

**Issue by protocold** [gwlim/openwrt-sfe-flowoffload#25]
Can you possibly build a WDR4300/MW4530R firmware that has 16mb flash instead of 8m? Many thanks!

**Comment by gwlim** [comment]
Have you tried flashing an 8MB SYSUPGRADE image (don't flash the factory) ? 
I have tried flashing 4MB image on 8MB Router and it works (but backup the ART partition before attempting this just in case)
My experience is that after the art partition the rest of the flash is formatted as jjfs and usable.

**Comment by gwlim** [comment]
Added MW4530Rv1
