### ISSUE TITLE
Switch from ar71xx to ath79 for routers like Archer C7?

### ISSUE THREAD

**Issue by Riotous** [gwlim/openwrt-sfe-flowoffload#26]
https://downloads.openwrt.org/snapshots/targets/ath79/generic/openwrt-ath79-generic-tplink_archer-c7-v2-squashfs-factory.bin

Apparently, ath79 snapshots will be the new default for Atheros based routers like the Archer C7 so will these builds also move to that?

**Comment by gwlim** [comment]
Will switch when the time comes, in terms of code updates it is the same, just without the DTS boot feature which has no effects on functionality, only during boot.

**Comment by MOZGIII** [comment]
What's DTS boot feature?

**Comment by gwlim** [comment]
DTS=Device Tree, the file extension is .dts so I usually call it DTS

**Comment by MOZGIII** [comment]
Oh, got it!
Btw, it seems to be solved with March release: https://github.com/gwlim/openwrt-sfe-flowoffload/blob/master/MAR-2019/openwrt-sfe-flowoffload-normal/TP-Link%20Archer%20C7v2-mips74k/openwrt-ar71xx-generic-archer-c7-v2-squashfs-factory.bin

We can close this issue  😊
