### ISSUE TITLE
Image for Raspberry 2

### ISSUE THREAD

**Issue by levipereira** [gwlim/openwrt-sfe-flowoffload#3]
There is a image for RPI Model 2?

**Comment by gwlim** [comment]
There is no point RPI Ethernet Port is connected via a USB 2.0 interface therefore cannot go to gigabit speeds.
It is a physical limitation.

**Comment by levipereira** [comment]
I plugged two Dongle Gbit on USB 2.0 interface and I can get 240 Mbit of throughput using iperf3, but the my router can get only 70MBit  when traffic pass from  WAN > LAN. I think is to related to NAT Translation.
That is the reason to ask.
Thank you anyway.
