### ISSUE TITLE
https dns proxy

### ISSUE THREAD

**Issue by MadRock88** [gwlim/openwrt-sfe-flowoffload#30]
any  body known how setup "https dns proxy with dnsmask"?
by "list server and noresolv 1" looks like it didnt work )))
if I right, dnsmask can't DOH, needed additional package like STUBBY
or I wrong?

maybe change "https dns proxy" to "stubby" in next release, if need DOH from box? )
or I dont known something)

**Comment by gwlim** [comment]
https dns proxy listens on 5054 or some ports you set
https dns proxy queries Cloudflare or Google DNS then dnsmasq queries https dns proxy on port 53
