### ISSUE TITLE
kmod-ipt-nathelper-rtsp

### ISSUE THREAD

**Issue by markouustalu** [gwlim/openwrt-sfe-flowoffload#31]
Hello,

I would like to use this module and i cannot:

The installed version of package kernel is not compatible, require 4.14.107-1-c41109cb… while 4.14.103-1-691562fa… is installed.

Readme said i should open an issue.

Router is Archer C7 v2 and i am using March 2019 build.

Thank you

**Comment by gwlim** [comment]
kmod tarball available with firmware image
