### ISSUE TITLE
Add SDCARD support for RB450G

### ISSUE THREAD

**Issue by eisengrau** [gwlim/openwrt-sfe-flowoffload#34]
Hello,

Is it possible to request to add support for MicroSD card for the Mikrotik RouterBoard RB450G release? Also this model does not  have USB at all, and I noticed in the software packages there are a lot of usb-* kmod-usb* packages. If the hardware is not there are these packages needed for core functionality / can they be removed from this build?

Thank you.

**Comment by gwlim** [comment]
Moved most of the USB kmods into a separate tarball
