### ISSUE TITLE
 Enable CONFIG_KERNEL_MIPS_FPU_EMULATOR would be nice

### ISSUE THREAD

**Issue by shing3232** [gwlim/openwrt-sfe-flowoffload#35]
Same as title

Thanks，

**Comment by gwlim** [comment]
If it doesn't contribute to the function the additional code will bloat the firmware image. Any use for it?

**Comment by shing3232** [comment]
Some binary require FPU support like v2ray, thanks.

**Comment by gwlim** [comment]
Added in AUG Image
