### ISSUE TITLE
Add wireguard support to 1043ND v1 (32 MB RAM) mini build

### ISSUE THREAD

**Issue by eisengrau** [gwlim/openwrt-sfe-flowoffload#38]
Hello,

Since this is still a very popular device, and shortcut-fe breathes new life in these "legacy" devices. Is it possible to enable the super awesome wireguard kernel modules (and luci interface supporting packages) for it? I noticed that there is still some space left in the flash after this any way.

Thank you!

**Comment by gwlim** [comment]
kmod added with fimware image including wireguard kmod
