### ISSUE TITLE
UniFi AP AC Lite

### ISSUE THREAD

**Issue by Manawyrm** [gwlim/openwrt-sfe-flowoffload#39]
Hi,

could you build a firmware image for the UniFi AP AC Lite? 
It's QCA9563/mips_24kc, so that should work pretty well, I hope. 

As far as I can see, the performance is completely limited by ksoftirqs, so this could maybe improve with your modifications. 

When building the firmware, please don't use kmod-ath10k-ct, but rather kmod-ath10k. It's newer and works stabler in my testing. 

Thanks,
Tobias

**Comment by gwlim** [comment]
Support added.
Recently I tested ath10k vs ath10k-ct with my intel ac 7265 adapter.
There is a very big improvement and stability in ath10k-ct around 400+Mbps hence I switched to ath10k.
