### ISSUE TITLE
nlbwmon high CPU usage

### ISSUE THREAD

**Issue by MadRock88** [gwlim/openwrt-sfe-flowoffload#45]
idk why, but on 600 mbit bandwight on 4300 (ipv4/ipv6)
nlbwmon load CPU to 1.00 and above, even when idle
it was 3-4 past firmware too
normal or not - idk
after disabling - load to CPU parallel to channel load

**Comment by gwlim** [comment]
I am not really sure it is an issue or not but you can try increasing polling interval of luci?
/etc/config/luci -> pollinterval

**Comment by markouustalu** [comment]
I can confirm, i had the same problem on Archer C7 v2, high cpu usage did not come right after reboot, it took a while. I noticed it week or two later. Disabling daemon resolves the problem.

**Comment by MadRock88** [comment]
I try increas interval. Maybe add another interval for cleaning logs(1week for example) in luci dropdown menu:) on Last firmware i take this load after ~5 min uptime

**Comment by gwlim** [comment]
Anyway i noticed I did an optimization wrongly on mips74k arch, packing the struct drop performance, but I am too lazy to redo the images will stage it for next release.

**Comment by gwlim** [comment]
Anyway I just bought a new Intel Wireless AX200 Card. 
The Intel AC 9260 is buggy DO NOT BUY. Buy the Intel Wireless AX200 card instead!

**Comment by Pentaphon** [comment]
@gwlim has this been fixed?

**Comment by gwlim** [comment]
I am not sure it has been fix LuCI went through some overhaul in Trunk.
Now they are using JS to render the views, I had to rewrite the SFE activation view.
