### ISSUE TITLE
K2T out of memory and load is too high

### ISSUE THREAD

**Issue by yy0c** [gwlim/openwrt-sfe-flowoffload#46]
![屏幕快照 2019-06-15 下午1 22 21](https://user-images.githubusercontent.com/1238163/59547423-53b5a380-8f71-11e9-898a-0313f0d2658e.png)
Luci and SSH is responsive only for less than about 30 seconds, I've not changed any setting. I have no idea what's happening, would you please help me investigate this bug?

**Comment by gwlim** [comment]
I can't see the full logs.
Copy and paste it here

**Comment by yy0c** [comment]
> 在 2019年6月15日，19:11，gwlim <notifications@github.com> 写道：
> 
> I can't see the full logs.
> Copy and paste it here
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Which ones do you need me to send?

**Comment by gwlim** [comment]
The whole top log which processes are taking how much RAM

**Comment by yy0c** [comment]
The weird thing is,  after waited for a minute or two, the system would be responsive again.  I guess we can close this issue for now, if you agree.

**Comment by gwlim** [comment]
Sure if it works great :)
