### ISSUE TITLE
Unable to install Upnp module :(

### ISSUE THREAD

**Issue by Zsolteeca** [gwlim/openwrt-sfe-flowoffload#48]
When I try to install the universal plug and play module to Fastpath Lede (ver june2019) 

**

> Details for package luci-app-upnp
> 
>     Version: git-19.183.27706-2d1d855-1
>     Size: ~3.6 KB installed
>     Dependencies:
>         miniupnpd (55.7 KB) Not installed
>             iptables Installed
>                 libpthread Installed
>                     libgcc1 Installed
>                 kmod-ipt-core Installed
>                     kernel Installed
>                     kmod-nf-reject Installed
>                     kmod-nf-ipt Installed
>                 libip4tc0 Installed
>                     libxtables12 Installed
>                 libip6tc0 Installed
>             libip4tc2 Not available
>             libip6tc2 Not available
>             ip6tables Installed
>                 kmod-ip6tables Installed
>                     kmod-nf-reject6 Installed
>                     kmod-nf-ipt6 Installed
>             libuuid1 (12.1 KB) Not installed
>                 librt (124 B) Not installed

**

I get the following message:

    Required dependency package libip4tc2 is not available in any repository.
    Required dependency package libip6tc2 is not available in any repository.

When I try to install the older version I get the same message :(
I 
Can anyone else been experienced about this problem?

opkg update command has been sent with 0 result..

**Comment by gwlim** [comment]
Upstream snapshot switched should be solved I have also included the pkg in the tar.gz
