### ISSUE TITLE
Please keep update your firmware!

### ISSUE THREAD

**Issue by Zsolteeca** [gwlim/openwrt-sfe-flowoffload#49]
The June version is really outdated :( 
Please give a newer version of components because some of the software elements are unusable.

Thank you!

**Comment by gwlim** [comment]
Yep I understand there is a lot of big change from upstream
Next release is almost ready but I need to fix a couple of bugs I discovered especially when it impacts performance.

**Comment by gwlim** [comment]
Looks like they did a large scaled change on LuCI again

**Comment by Zsolteeca** [comment]
What kind of changes did they "commit"?

**Comment by gwlim** [comment]
From Lua render of views to javascript render of views

**Comment by Zsolteeca** [comment]
I am looking forward to a new version of fastpath lede

**Comment by Zsolteeca** [comment]
When will it be available?

**Comment by gwlim** [comment]
There is a serious bug I discovered.
https://bugs.openwrt.org/index.php?do=details&task_id=2364&order=dateopened&sort=desc
If your router gets a flood of UDP traffic your router can run out of memory and crash, upstream issue with kernel 4.19

**Comment by Zsolteeca** [comment]
:(
You can always find bugs.. Every release of openwrt contains bugs..
I am waiting for a Fastpath Lede new actual release..
Probably a bug fix could be released for errors. You have a module attended system updates 
attendedsysupgrade-common and will it be work? Because I have a message that my router isn't supported..

**Comment by gwlim** [comment]
I sort of understood the bug and alleviated the issue on WR1043NDv1.
Now I am testing it on my network.
I am going to dump http-dns-proxy because the author made some changes and cause unaligned memory access on MIPS cpu.

**Comment by Pentaphon** [comment]
@gwlim Thanks for keeping this firmware updated. I look forward to your next release.

**Comment by gwlim** [comment]
Released AUG
