### ISSUE TITLE
Too less space to install other components to luci

### ISSUE THREAD

**Issue by Zsolteeca** [gwlim/openwrt-sfe-flowoffload#51]
Could you seperate more space to Luci software section? Because I only have approx. one MB to install anything what I would like to have on Luci or upgrade modules. 
Or what does it depend on how many space could I have on this section?

Thanks for answer!

**Comment by gwlim** [comment]
What hardware are you using?

**Comment by Zsolteeca** [comment]
Tplink WR1043ND v2 hardware

**Comment by gwlim** [comment]
Removed a few packages by default in AUG
