### ISSUE TITLE
Slow ipv6 with pppoe

### ISSUE THREAD

**Issue by kolomparrudi** [gwlim/openwrt-sfe-flowoffload#53]
Hi,

My ISP (Digi Hungary) offers ipv6 in shared session with ipv4.
I have a TL-WR1043N/ND v3, with your June image, ipv4 benchmark results are 300-350 Mbps, ipv6 is around 100 Mbps. There is no difference in ipv6 speed if I stop shortcut-fe service.

Also have some questions about sfe: What is the difference between your fastpath sfe solution and the flow offloading offered by the latest openwrt snapshots? Do you have benchmarks which solution performs better? Do you think using real hardware offloading with AR8327n we can reach higher throughput?

Thanks,
Kolomparrudi

**Comment by gwlim** [comment]
Do cat /sys/fast_classifier/debug_info to see if IPv6 is offloaded

**Comment by gwlim** [comment]
Can also be due to bandwidth limitation set by website?

**Comment by kolomparrudi** [comment]
Hi,

Checked the /sys/fast_classifier/debug_info, but only ipv4 connections present here. It seems my ipv6 connections are not offloaded.

I have already tested the bandwidth with multiple sites and with iperf3 and wget download too.

**Comment by gwlim** [comment]
When I tested IPv6 static routing I can see the offload but not sure why it doesn't work in actual deployments. I need to troubleshoot this.

**Comment by kolomparrudi** [comment]
If you need logs/debug/existing config/etc I'll try to help you.

**Comment by gwlim** [comment]
Issue should be fixed tested with IPv6 enabled ISP
