### ISSUE TITLE
TP-Link WR1043NDv1-32MB-RAM-mips24k-ath9k

### ISSUE THREAD

**Issue by Vik-Osa** [gwlim/openwrt-sfe-flowoffload#55]
openwrt-sfe-flowoffload/AUG-2019/openwrt-sfe-flowoffload-mini/TP-Link WR1043NDv1-32MB-RAM-mips24k-ath9k/openwrt-ath79-generic-tplink_tl-wr1043nd-v1-squashfs-factory.bin

Firmware installed. The router has earned. Problem: Does not save settings in LuCI. Such an impression that there is not enough memory. Hangs on trying to save the changed settings. Only after the router itself cleared its memory, closing unnecessary programs, was it possible to partially save the settings.

**Comment by Vik-Osa** [comment]
Ready to help test:
openwrt-sfe-flowoffload-mini/TP-Link WR1043NDv1-32MB-RAM-mips24k-ath9k/openwrt-ath79-generic-tplink_tl-wr1043nd-v1-squashfs-factory.bin

**Comment by gwlim** [comment]
Issue should be fixed, tested with IPv6 ISP provider.
