### ISSUE TITLE
Install after a install of openwrt 

### ISSUE THREAD

**Issue by zanguigui** [gwlim/openwrt-sfe-flowoffload#59]
Hi ! 
I currently use A stock openwrt on a Archer c7 and a RE450
Do I have to do a factory flash or can I use the sysupgrade of your firmware ? 
Thx

**Comment by zanguigui** [comment]
And last question 
If I have to use the factory 
Can I use the save file of my conf ?

**Comment by gwlim** [comment]
Factory = Stock Firmware -> OpenWRT
Sysupgrade = OpenWRT -> OpenWRT
Stock Firmware Config cannot be used in OpenWRT
Reset and start over
