### ISSUE TITLE
Missing Cake Queuing Discipline

### ISSUE THREAD

**Issue by komawoyo** [gwlim/openwrt-sfe-flowoffload#6]
Ty for the builds! 

WDR3600v1
JAN2019 firmware (normal - ie not mini)

missing cake queuing discipline, sqm scripts installed (sqm-scripts, luci-app-sqm)

![image](https://user-images.githubusercontent.com/18315233/49688480-bd875900-fac7-11e8-8326-8d1ddfbec834.png)

**Comment by gwlim** [comment]
Try go to SYSTEM- > STARTUP
ENABLE and START SQM
Then go to luci-sqm and choose CAKE

**Comment by komawoyo** [comment]
Ty! this fixed it, oddly, I had to restart the service and reboot a few times to get it working. This is definitely on my end though.

**Comment by Riotous** [comment]
@gwlim You may want to put this information in an FAQ because I was looking for the answer to this issue for a while until by chance I looked into these closed issues.

**Comment by vicodin99** [comment]
Same as ghost here, @gwlim . Was about to report this as an issue until github suggested to look at this thread. It would be nice if this was added as part of the FAQ.

At least for me, I uninstalled luci-app-sqm and reinstalled it, then cake appeared in the drop down menu.
