### ISSUE TITLE
PPOE connecting problem

### ISSUE THREAD

**Issue by Zsolteeca** [gwlim/openwrt-sfe-flowoffload#60]
When I restart the router (Tplink WR1043 ND V2) I got the following message and it shows for about ten or a little more times but the end of it,it will connect to the ppoe network successfully.. 

"Tue Aug  6 00:06:27 2019 daemon.warn pppd[2391]: Timeout waiting for PADO packets
Tue Aug  6 00:06:27 2019 daemon.err pppd[2391]: Unable to complete PPPoE Discovery
Tue Aug  6 00:06:27 2019 daemon.info pppd[2391]: Exit."

:( is it for the firmware or anything else? I do not know.

**Comment by gwlim** [comment]
Does it work?
It could be an ISP Configuration thing

**Comment by Zsolteeca** [comment]
Oh,thanks.
