### ISSUE TITLE
Help installing flow offload on AUG image

### ISSUE THREAD

**Issue by vlados-debug** [gwlim/openwrt-sfe-flowoffload#62]
I understand flow offload was removed in the aug image but it gave me 3x faster irl speeds than the latest sfe. I'm not very experienced when it comes to router firmware so was wondering how I install the flow offload from the tar ball archive. Sorry for the super dumb question

**Comment by Pentaphon** [comment]
@vlados-debug are you using the Archer C7 V2? I also found Flow Offload to be much faster than SFE on that device.

**Comment by gwlim** [comment]
Included
