### ISSUE TITLE
Support an new router.

### ISSUE THREAD

**Issue by Axius** [gwlim/openwrt-sfe-flowoffload#64]
Can you please add support for TP-Link Archer C6v2.
That would be greatly appreciated.

Thanks,

**Comment by kolomparrudi** [comment]
@gwlim: it would be fine if you can share (or update mips74k-ar71xx-lede-patch repo) your current script and sources for patching to able to add new router by the community. I have a new Xiaomi router 3G and I have issues with the latest openwrt flow offload feature (remote desktop lagging, disconnectiong) and I'd like to try sfe there.

Thanks,

**Comment by gwlim** [comment]
> 
> 
> @gwlim: it would be fine if you can share (or update mips74k-ar71xx-lede-patch repo) your current script and sources for patching to able to add new router by the community. I have a new Xiaomi router 3G and I have issues with the latest openwrt flow offload feature (remote desktop lagging, disconnectiong) and I'd like to try sfe there.
> 
> Thanks,

I am working on mips1004kc as I have a Newifi-D2

> 
> 
> Can you please add support for TP-Link Archer C6v2.
> That would be greatly appreciated.
> 
> Thanks,

Added in SEP Image
