### ISSUE TITLE
Please Explain me about Flow offloading via SFE!

### ISSUE THREAD

**Issue by Zsolteeca** [gwlim/openwrt-sfe-flowoffload#65]
I have problems with port forwardings in Firewall.
 If I turn off the SFE based Flow offload the connection phases are okay and I can login successfully to my ftp server to my router and to the RDC connection for example..
The port forward are "in function to open" is okay they are opened.. but in the SSL/TLS part of the authentication they are "halt" for example on FTP stuck on the SSL on the RDC connections stuck on the "securing" :( 

Why could it be? 
How does the SFE based Flow offload work? I tried to find something about this,but I can't understand the point of it. And my current situation. :(

The previous version I think that SFE and flow offloading were seperately..

Thank you for the help!

**Comment by Patazerty** [comment]
Please see #61 , enabling SFE can break port forwarding.
