### ISSUE TITLE
forward 443 and 80 on AUG version

### ISSUE THREAD

**Issue by gpopesc** [gwlim/openwrt-sfe-flowoffload#66]
Hi

I have been using since last year your version of openwrt and it is great, much faster than factory version on my Archer C7 V2.
When I did last AUG update everything worked fine, except the port forwarding to my NAS on ports 80 and 443. The NAS respond, but it doesn't display the page. I tried to reset the router, but I got the same result.
The June version is working fine.

**Comment by Zsolteeca** [comment]
https://github.com/gwlim/openwrt-sfe-flowoffload/issues/61

There is the problem 

I hope that it will be solved lately in the recent version of Fastpath Lede..

**Comment by gwlim** [comment]
Should be fixed
