### ISSUE TITLE
Slow download speed using openwrt-sfe.

### ISSUE THREAD

**Issue by Axius** [gwlim/openwrt-sfe-flowoffload#71]
Hello,
I have a problem with the download speed using  TP-Link Archer C6 v2 (EU).
I have gigabit connection form my ISP.

The speeds I get now -> 130 Mbps Download
                                   -> 415 Mbps Upload.

Can you help me fix this problem.

**Comment by Xmister** [comment]
Do you have SFE enabled in Network/Firewall?
![alt text](https://raw.githubusercontent.com/gwlim/openwrt-sfe-flowoffload/master/sfe-offload-1.PNG)

**Comment by Axius** [comment]
I've enabled SFE flow offloading.

**Comment by Axius** [comment]
Do I have any options this fix this problem?

**Comment by gwlim** [comment]
Reboot after enabling SFE
If you are using speedtest try changing servers.
Test using direct connection from computer to modem

**Comment by gwlim** [comment]
I will be closing this if there is no response.
