### ISSUE TITLE
TP-Link Archer A7 v5

### ISSUE THREAD

**Issue by panama007** [gwlim/openwrt-sfe-flowoffload#73]
Could we get a build for the Archer A7 v5. It's supposedly the same hardware as the Archer C7 v5, but with a [different flash layout](https://forum.openwrt.org/t/support-for-archer-a7/20790)? Any help is appreciated.

**Comment by gwlim** [comment]
Added Test Image

**Comment by panama007** [comment]
With the test image I was able to see 850 Mbps on fast.com whereas before it topped out at like 210. I haven't yet tested it with iperf, but it seems to be working. Thank you very much!
