### ISSUE TITLE
hw nat

### ISSUE THREAD

**Issue by kfur** [gwlim/openwrt-sfe-flowoffload#80]
Why did you abandon QCA Hardware NAT support ? As i understood your old repo supported it.

**Comment by kolomparrudi** [comment]
According to the openwrt forum in thread (https://forum.openwrt.org/t/hardware-nat-for-lede/1094), the HW NAT didn't work. The QCA-SSDK successfully integrated into LEDE, but nobody knows how to config switch registers to activate HW NAT.

If somebody has a lot of free time, it may be possible to dump the config (create a modified stock image with telnet/ssh) and add QCA-SSDK-SHELL.

**Comment by kfur** [comment]
@kolomparrudi thanks for reply. will try to play around with ssdk-shell.
