### ISSUE TITLE
SEPT firmware wdr-4300 - (kernel packages archive)

### ISSUE THREAD

**Issue by asergiu** [gwlim/openwrt-sfe-flowoffload#82]
Hi gwlim,
   On the sept build the archive with the kernel modules has a mismatch in the hash of of the kernel 
Trying to install kmod-nf-nathelper-extra_4.19.72-1_mips_24kc.ipk from archive:
_opkg install /tmp/kmod-nf-nathelper-extra_4.19.72-1_mips_24kc.ipk
Installing kmod-nf-nathelper-extra (4.19.72-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-nf-nathelper-extra:
 *      kernel (= 4.19.72-1-23e25f21c0f86dda925f0fc261a08d10)
 * opkg_install_cmd: Cannot install package kmod-nf-nathelper-extra._

kernel 
_opkg info kernel
Package: kernel
**Version: 4.19.72-1-54da640ce96c5aae929223a4b7298832**
Depends: libc, libpthread
Status: install user installed
Architecture: mips_24kc
Installed-Time: 1568473905_

Would it be possible to fix the kernel modules archive ? (rebuild module packages with the correct kernel ?)

Thx
Adrian

**Comment by gwlim** [comment]
Are you sure you installed the kmods correctly?
1)Extract the kmods
2)scp the kmods to router /tmp/
3)opkg install /tmp/<kmod file>
You need to specify FULL PATH if not it is installing from openwrt upstream repo

**Comment by asergiu** [comment]
I extracted them from tar. You answered me at that time ... I will try this evening as it is at my home. Anyway you told me to install another version of your build and on that one it worked.
Adrian
    On Thursday, 19 December 2019, 13:08:11 EET, gwlim <notifications@github.com> wrote:  
 
 
Are you sure you installed the kmods correctly?
1)Extract the kmods
2)scp the kmods to router /tmp/
3)opkg install /tmp/
You need to specify FULL PATH if not it is installing from openwrt upstream repo

**Comment by taz-1** [comment]
I also have the same error when installing packages, I think the error is kernel compatibility

**Comment by gwlim** [comment]
The issue should not be present in the December version
Please test before making outdated comments.

**Comment by asergiu** [comment]
Dear gwlim    I am far away from commenting. I do appreciate your work. I only thought my statement would help you pinpoint things in some of the builds. Now I have a version (need to look which one) that works more or less for what I need. If you need me to test a new one (if that would help you) just let me know.AdrianOn 22 Dec 2019 09:18, gwlim <notifications@github.com> wrote:The issue should not be present in the December version
Please test before making outdated comments.
