### ISSUE TITLE
Netgear WNDR4300 v1 is missing in the newest build.

### ISSUE THREAD

**Issue by spamsool** [gwlim/openwrt-sfe-flowoffload#84]
Hello
I have noticed that Netgear WNDR4300 v1 is missing in the newest build.
Could you be so kind and continue building the image for this device. It was present in the previous build and was working flawlessly.
Thanks very much for help ;)

**Comment by gwlim** [comment]
Migrate it to ath79 and I will build it

**Comment by spamsool** [comment]
It is now migrated to ath79 Could you please start building firmware for it please??

**Comment by gwlim** [comment]
It is already included.
