### ISSUE TITLE
NOV release?

### ISSUE THREAD

**Issue by oriceon** [gwlim/openwrt-sfe-flowoffload#91]
Hi. Can you publish a Nov release?

**Comment by Zsolteeca** [comment]
It would be good..

**Comment by Zsolteeca** [comment]
But nothing :'(

**Comment by oriceon** [comment]
Yes.. I still waiting for it.

**Comment by Zsolteeca** [comment]
First of December will come.. :(

**Comment by Zsolteeca** [comment]
This is outdated :( really outdated now :( :'(

**Comment by Zsolteeca** [comment]
DEC release?

**Comment by gwlim** [comment]
Added
