### ISSUE TITLE
Where is "Gwlim"? :(

### ISSUE THREAD

**Issue by Zsolteeca** [gwlim/openwrt-sfe-flowoffload#98]
Where is "Gwlim"? :(

**Comment by xchwarze** [comment]
@Zsolteeca please stop creating junk issues.
gwlim will answer when he has time to do it

**Comment by Zsolteeca** [comment]
But has away for about two months :( I think that he hit by the train or whatsever..

**Comment by vicodin99** [comment]
@Zsolteeca 

gwlim will answer when he can or update when there's a need. He's a busy person.

Please, stop. You're not helping by spamming junk issues. Your time would be better used if you tried to improve your English. Meanwhile, enjoy these builds as they are, if they're useful to you.

**Comment by Zsolteeca** [comment]
You are a clever bullshit vlcodin..

I had to reset the router for a reason.. For example a latest build has really outdated.. Because of software components I use dyndns.. and a few more don't compatible with this firmware because of the environment.. version changes usually two days...  And I can update this whole system in vain because versions will be incompatible with others.. That's why...
