### ISSUE TITLE
Port forward not working

### ISSUE THREAD

**Issue by robinhugy** [gwlim/openwrt-sfe-flowoffload#99]
Port forwards not working for me, portscan says Port Status: closed

WDR4300 | OpenWrt SFE r11009-1cf2495d48

**Comment by robinhugy** [comment]
port forward working with dec 2019 image but have sfe offloading problem, its slower than old image
old: stable 350-450 mbit
new: starting with 400+ but a few secs later the max speed is only 250-280 mbit

**Comment by robinhugy** [comment]
tried all options in firewall:

SFE flow offloading

Software flow offloading /
Software based offloading for routing/NAT
Hardware flow offloading

**Comment by 0sy** [comment]
Using pppoe by chance? The overhead is what kills the speed

**Comment by 0sy** [comment]
> port forward working with dec 2019 image but have sfe offloading problem, its slower than old image
> old: stable 350-450 mbit
> new: starting with 400+ but a few secs later the max speed is only 250-280 mbit

Using pppoe by chance? Some users report slowness when on pppoe, and it's probably due to the overhead.

**Comment by robinhugy** [comment]
WAN - Protocol: DHCP client

the config is same like in the old version, nothing changed only firmware

**Comment by gwlim** [comment]
port forwarding is not SFE accelerated because there is no NAT

**Comment by robinhugy** [comment]
but port forwarding is does not affect speedtest.net

**Comment by gwlim** [comment]
Try the latest

**Comment by robinhugy** [comment]
oh just see jan 2020, thanks for notice
what "il" means in firmware name? e.g. openwrt-ath79-generic-tplink_tl-wdr4300-v1-**### il**-squashfs-factory.bin

**Comment by aszorenyi** [comment]
It means that its for WDR4300 bought in Israel. If you check the product page on OpenWRT site you can see. :)

**Comment by robinhugy** [comment]
checked openwrt site but i never seen, thanks Ádám :)
